version: "3"
services:
  app:
    image: ghcr.io/simerca/itpmarket:latest
    labels:
      - traefik.enable=true

      - traefik.http.routers.itpmarket-http.entrypoints=web
      - traefik.http.routers.itpmarket-http.rule=Host(`${HOSTNAME}`)

      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.itpmarket-http.middlewares=https-redirect@docker

      - traefik.http.routers.itpmarket-https.entrypoints=websecure
      - traefik.http.routers.itpmarket-https.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.itpmarket-https.tls=true
      - traefik.http.routers.itpmarket-https.tls.certresolver=letsencrypt
      - traefik.http.services.itpmarket.loadbalancer.server.port=5000
    networks:
      - web

networks:
  web:
    external: true
