version: "3"
services:
  app:
    image: ghcr.io/simerca/itpmarket:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=5000"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=le"
    networks:
      - web
    ports:
      - 5002:5000

networks:
  web:
    external: true
